/* XPM */
static char * cdrom_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray2	m white	c #bdbdbdbdbdbd",
"X	s iconColor3	m black	c red",
"o	s iconColor6	m white	c yellow",
"O	s iconColor7	m white	c cyan",
"+	s iconColor4	m white	c green",
"@	s iconColor2	m white	c white",
"#	s iconGray6	m black	c #636363636363",
"$	s iconColor5	m black	c blue",
"%	s iconColor1	m black	c black",
/* pixels */
"                                ",
"            ........            ",
"         ..............         ",
"       ..XX..............       ",
"      ..ooX...............      ",
"     .O++oX........@@.....#     ",
"    .O$O+ooX.........@@....#    ",
"   ..+O$O+oX...........@...##   ",
"   .o++O$OoXX......@@...@...#   ",
"  .Xooo+O$OoX........@...@...#  ",
"  .XXXoooO$+XX........@..@...#  ",
"  ....XXXo+$oX@@@@.....@..@..#  ",
" .......XXXo$@%%%%@....@..@...# ",
" .........XX@%@@@@%@..........# ",
" ..........@%@@%%@@%@.........# ",
" ..........@%@%%%%@%@.........# ",
" ..........@%@%%%%@%@.........# ",
" ..........@%@@%%@@%@.........# ",
" ...........@%@@@@%@XX........# ",
" ....@..@....@%%%%@$oXXX......# ",
"  ...@..@.....@@@@Xo$ooXXX...#  ",
"  ....@..@........XX+$OoooXXX#  ",
"  ....@...@........XoO$O+oooX#  ",
"   ....@...@@......XXoO$O++o#   ",
"   .....@...........Xo+O$O+##   ",
"    .....@@.........Xoo+O$O#    ",
"     ......@@........Xo++O#     ",
"      ##.............Xoo##      ",
"       ##............XX##       ",
"         ###........###         ",
"            ########            ",
"                                "};
