/* XPM */
static char * Emacs_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	c #F4F4A4A46060",
"o	s iconColor2	m white	c white",
"O	c #BEBEBEBEBEBE",
"+	s iconColor5	m black	c blue",
"@	c #8B8B45451313",
/* pixels */
"                                                ",
"                                   .            ",
"                                    X.          ",
"                                    XXX.        ",
"                                      XX.       ",
"          .                             XX.     ",
"         .X                ...          XXX.    ",
"        .X           ... ...X...         .XX.   ",
"       .XX       ....XX...XXXXX..        .XX.   ",
"      .XX       .XXXXXXX..XXXXXX..       .XX.   ",
"      .XX      ..XXXXXXXX.XXXXXXX..     ..XX.   ",
"     .XX      ..XXXXXXXXXXXXXXXXXX.    ..XX..   ",
"    .XX.     ..XXXXX...XXXXXXX...X... ..XXX..   ",
"   .XXX.    ..XXXXX..ooo...............XXX..    ",
"   .XXX.   ..XXXXXX..oo...ooo....ooo........    ",
"   .XXX.   .XXXXXX..o...ooooooo.o.ooooooo....   ",
"   .XXX.. .XXX.XX..o..oooooooooo.o..ooooooooo.  ",
"   .XXXX..XX..XXX.o..ooooOOOO.O.O.OOo...ooooo.  ",
"   ..XXXX....XX..o..o....oOOOOOOOo...    ....   ",
"    ..XXXXXXXX..oo.o...ooOOOOOOOOOo..           ",
"    ...XXXXX...oo..o..o..o...oOOOOOo..          ",
"      ...XX..ooo..o..o++++oo..OOOOOO..          ",
"       ....ooooo..o..++X++o..OOOOOOO..          ",
"        ..ooooo..ooo.o+++.o...OOOOOO..          ",
"       .oooo....oo..ooo...OOOOOOOOOO..          ",
"       .oo......oo.ooooooo.ooOOOOOOOO..         ",
"       .o. ...o.o.o.ooo....oOOOOOOOOO..         ",
"        .  ...o.o.o..ooo..ooOOOOOOOOO..         ",
"          ..o.oo.o.o..ooooooooOOOOOOOO.         ",
"         ..Oo..o.o.o.o.oooooooOOOOOOOOO.        ",
"         ..Ooo....oo.ooo.oooooooOOOOOOO.        ",
"         ..OOo..o.oo..ooo.oooooooOOOo...        ",
"         ..OOoo.o.o.o.o.o..o.....oOo..@..       ",
"         ..OOoo.o..oo..o.o.o.@@@.....@@@.       ",
"         ..OOOo.oo...o.o.o.o.@@@@@...@...       ",
"          ..OOo..oo.oo..o....@@.@@@.@@...       ",
"          ..OOoo..o...o...o...@@..@.@@..        ",
"           ..OOOo..o..oo..o....@@.@@@...        ",
"           ..OOOo...o..o.........@@@@...        ",
"            ..OOooo..o..o......@@.......        ",
"            ..OOOOoo.oo...oo....@@@@@..         ",
"             ..OOOOoo.oo..oo....@@@@..          ",
"              ...OOOOO.o..o...........          ",
"               ...OOOOOoo...    .....           ",
"                ....OOOO....                    ",
"                  ...OOO...                     ",
"                    .....                       ",
"                                                "};
