/* XPM */
static char * Emacs_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #F4F4A4A46060",
"X	s iconColor1	m black	c black",
"o	s iconColor2	m white	c white",
"O	c #BEBEBEBEBEBE",
"+	s iconColor5	m black	c blue",
"@	c #8B8B45451313",
/* pixels */
"                                ",
"                                ",
"                        ..X     ",
"                          .X    ",
"      X.          XX       ..X  ",
"      .       XX XX.XX      ..  ",
"    X.     X....XX....X     ..  ",
"    X.    XX.....X....XX   X..  ",
"   X.X   X....XX....XX.XX X..X  ",
"  X..X  XX...XooXXXXXXXXXX..XX  ",
"  X..X  ....XXXXoooooXXoooooXX  ",
"  X..X X....XoXooooooooXooooooX ",
"  XX..XXX.XXXXXXXoOOOOoXX   XX  ",
"   X......XoXoXXoOOOOOOoX       ",
"    XX..XooXoXo+++oXOOOOXX      ",
"     XXXoooXoX++++XXOOOOXX      ",
"     XooXXXoXXooXXOOOOOOXX      ",
"     XoXXXXoXoooooooOOOOOX      ",
"        XXXooXooXXoOOOOOOX      ",
"       XoXoXXoXoooooOOOOOO      ",
"      XXooXXooooXoooooOOOOX     ",
"      XXOoXoooXooXooooOOoXX     ",
"      XXOoXoXoXXXooX@@XXX@@X    ",
"      XXOOXoXXoXXooX@@@XX@XX    ",
"       XOOoXoXXoXXXX@@X@@@X     ",
"        XOOoXoXoXXXXX@X@@XX     ",
"        XXOooXoXoXXXX@XXXXX     ",
"        XXOOooooXXoXXX@@@X      ",
"          XXOOOXXXXXXXXXXX      ",
"          XXOOOOoXX   XXX       ",
"            XXOOXX              ",
"              XXX               "};
