/* XPM */
static char * fig_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s none	m none	c none",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor1	m black	c black",
"O	s iconColor3	m black	c red",
"+	s iconColor4	m white	c green",
"@	s iconColor5	m black	c blue",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray7	m black	c #424242424242",
"%	s iconGray3	m white	c #adadadadadad",
/* pixels */
"                         .......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXOOOOOOXXXXXXXXXXXXXXo.......",
" XXOOOOOOOOXXXXXXXXXXXXXo.......",
" XOOOOOOOOOOXXXXXXXXXXXXo.......",
" XOOOOOOOOOOXXXXXXXXXXXXo.......",
" XOOOOOOOOOO+++++++++XXXo.......",
" XOOOOOOOOOO+++++++++XXXo.......",
" XOOOOOOOOOO+++++++++XXXo.......",
" XOOOOOOOOOO+++++++++XXXo.......",
" XXOOOOOOOOX+++++++++XXXo.......",
" XXXOOOO@OXX+++++++++XXXo.......",
" XXXXXX@@XXX+++++++++XXXo.......",
" XXXXX@@@XXX+++++++++XXXo.......",
" XXXX@@@@XXX+++++++++XXXo.......",
" XXX@@@@@XXXXXXXXXXXXXXXo.......",
" XX@@@@@@XXXXX##################",
" X@@@@@@@XXXXX#@$@$@$@$@$@$@$@$o",
" @@@@@@@@XXXXX#$    @   @$  @$@o",
" X@@@@@@@XXXXX#@ @$@$@ @$ $@ @$o",
" XX@@@@@@XXXXX#$ $@$@$ $@ @$@$@o",
" XXX@@@@@XXXXX#@   @$@ @$ $@$@$o",
" XXXX@@@@XXXXX#$ $@$@$ $@ @  $@o",
" XXXXX@@@XXXXX#@ @$@$@ @$ $@ @$o",
" XXXXXX@@XXXXX#$ $@$@   @$  @$@o",
" XXXXXXX@XXXXX#@$@$@$@$@$@$@$@$o",
" XXXXXXXXXXXXX#ooooooooooooooooo",
" XXXXXXXXXXXXX%%%%%%%%%%%.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" oooooooooooooooooooooooo......."};
