/* XPM */
static char * floppy_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s topShadowColor	m white	c #bdbdbdbdbdbd",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray4	m white	c #949494949494",
"O	s iconColor3	m black	c red",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s bottomShadowColor	m black	c #636363636363",
"#	s iconColor2	m white	c white",
"$	s iconGray8	m black	c #212121212121",
"%	s iconGray1	m white	c #dededededede",
/* pixels */
"  ...........................   ",
" .XXoOOOOOOOOOOOOOOOOOOOOO+XX.  ",
".XXXoOOOOOOOOOOOOOOOOOOOOO+XXX@ ",
".XXXo#####################+X$X@ ",
".XXXo#####################+X$X@ ",
".XXXo#++++++++++++########+XXX@ ",
".XXXo#####################+XXX@ ",
".XXXo#++++++++############+XXX@ ",
".XXXo#####################+XXX@ ",
".XXXo#####################+XXX@ ",
".XXXo#####################+XXX@ ",
".XXXo#####################+XXX@ ",
".XXXo#####################+XXX@ ",
".XXXo#####################+XXX@ ",
".XXXo#####################+XXX@ ",
".XXXo#####################+XXX@ ",
".XXX+++++++++++++++++++++++XXX@ ",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX@ ",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX@ ",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX@ ",
".XXXXXXXXoooooooooooooooooXXXX@ ",
".XXXXXXXXo++++++++++++oXX%%XXX@ ",
".XXXXXXXXo++++++++++++oXXX%XXX@ ",
".XXXXXXXXo++$$$$%+++++oXXX%XXX@ ",
".XXXXXXXXo++$ooo%+++++oXXX%XXX@ ",
".XXXXXXXXo++$ooo%+++++oXXX%XXX@ ",
".XXXXXXXXo++$ooo%+++++oXXX%XXX@ ",
".XXXXXXXXo++$ooo%+++++oXXX%XXX@ ",
".XXXXXXXXo++%%%%%+++++oXXX%XXX@ ",
" @XXXXXXXo++++++++++++oXXX%XX@  ",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@   ",
"                                "};
