/* XPM */
static char * flopdrv_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 8 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s topShadowColor	m white	c #bdbdbdbdbdbd",
"X	s iconGray4	m white	c #949494949494",
"o	s bottomShadowColor	m black	c #636363636363",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray5	m black	c #737373737373",
"@	s iconColor1	m black	c black",
"#	s iconGray8	m black	c #212121212121",
/* pixels */
"                                ",
"                                ",
"    ........................    ",
"   .XXXXXXXXXXXXXXXXXXXXXXXX.   ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .X........................Xo  ",
"  .X.OOOOOOOOOOOOOOOOOOOOOOoXo  ",
"  .X.OOOOOOOOOOOOOOOOOOOOOOoXo  ",
"  .X.OOOOOOOOOOOOOOOOOOOOOOoXo  ",
"  .X.OOOOOOOOOOOOOOOOOOOOOOoXo  ",
"  .X.OO+++++++++++++++++++OoXo  ",
"  .X.OO@@@@@@@@@@@@@@@@@@+OoXo  ",
"  .X.OOOOOOOO@@@@@@@OOOOOOOoXo  ",
"  .X.OOOOOOOOXXXXXXXOOOOOOOoXo  ",
"  .X.OOOOOOOOOOOOOOOOO##OOOoXo  ",
"  .X.OOOOOOOOOOOOOOOOO##OOOoXo  ",
"  .X.OOOOOOOOOOOOOOOOOOOOOOoXo  ",
"  .XooooooooooooooooooooooooXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"   oXXXXXXXXXXXXXXXXXXXXXXXXo   ",
"    oooooooooooooooooooooooo    ",
"                                ",
"                                "};
