/* XPM */
static char * Ftp_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 4 1 -1 -1",
/* colors */
" 	s topShadowColor	m white	c #bdbdbdbdbdbd",
".	s bottomShadowColor	m black	c #636363636363",
"X	s background	m black	c #949494949494",
"o	s iconColor1	m black	c black",
/* pixels */
"                                                ",
"                                               .",
"                                              ..",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...",
"   X....................................... X...",
"   X......................................  X...",
"   X..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X...",
"   X..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X...",
"   X..XXXoooooooooXoooooooooXoooooooXXXXXX  X...",
"   X..XXXoooooooooXoooooooooXoooooooooXXXX  X...",
"   X..XXXoooooooooXoooooooooXooooooooooXXX  X...",
"   X..XXXoooXXXXXXXXXXoooXXXXoooXXXXoooXXX  X...",
"   X..XXXoooXXXXXXXXXXoooXXXXoooXXXXXoooXX  X...",
"   X..XXXoooXXXXXXXXXXoooXXXXoooXXXXXoooXX  X...",
"   X..XXXoooXXXXXXXXXXoooXXXXoooXXXXoooXXX  X...",
"   X..XXXooooooXXXXXXXoooXXXXooooooooooXXX  X...",
"   X..XXXooooooXXXXXXXoooXXXXoooooooooXXXX  X...",
"   X..XXXooooooXXXXXXXoooXXXXoooooooXXXXXX  X...",
"   X..XXXoooXXXXXXXXXXoooXXXXoooXXXXXXXXXX  X...",
"   X..XXXoooXXXXXXXXXXoooXXXXoooXXXXXXXXXX  X...",
"   X..XXXoooXXXXXXXXXXoooXXXXoooXXXXXXXXXX  X...",
"   X..XXXoooXXXXXXXXXXoooXXXXoooXXXXXXXXXX  X...",
"   X..XXXoooXXXXXXXXXXoooXXXXoooXXXXXXXXXX  X...",
"   X..XXXoooXXXXXXXXXXoooXXXXoooXXXXXXXXXX  X...",
"   X..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X...",
"   X..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X...",
"   X..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X...",
"   X..XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX  X...",
"   X..XXXXXX  XXXXXXXXXXXXXXXXXX  XXXXXXXX  X...",
"   X..XXXXX   XXXXXXXXXXXXXXXXXX   XXXXXXX  X...",
"   X..XXXX   X                  X   XXXXXX  X...",
"   X..XXX   XX                  XX   XXXXX  X...",
"   X..XX   XXX                  XXX   XXXX  X...",
"   X..X   XXXXXXXXXXXXXXXXXXXXXXXXXX   XXX  X...",
"   X..   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX  X...",
"   X..X...XXXXXXXXXXXXXXXXXXXXXXXXXX...XXX  X...",
"   X..XX...XXX..................XXX...XXXX  X...",
"   X..XXX...XX..................XX...XXXXX  X...",
"   X..XXXX...X..................X...XXXXXX  X...",
"   X..XXXXX...XXXXXXXXXXXXXXXXXX...XXXXXXX  X...",
"   X..XXXXXX..XXXXXXXXXXXXXXXXXX..XXXXXXXX  X...",
"   X..XXXXXXX.XXXXXXXXXXXXXXXXXX.XXXXXXXXX  X...",
"   X..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X...",
"   X.                                       X...",
"   X                                        X...",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...",
"  ..............................................",
" ..............................................."};
