/* XPM */
static char * Ftp_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 4 1 -1 -1",
/* colors */
" 	s topShadowColor	m white	c #bdbdbdbdbdbd",
".	s bottomShadowColor	m black	c #636363636363",
"X	s background	m black	c #949494949494",
"o	s iconColor1	m black	c black",
/* pixels */
"                                ",
"                               .",
"  XXXXXXXXXXXXXXXXXXXXXXXXXXXX..",
"  X......................... X..",
"  X.XXXXXXXXXXXXXXXXXXXXXXXX X..",
"  X.XXXXXXXXXXXXXXXXXXXXXXXX X..",
"  X.XXXXXXXXXXXXXXXXXXXXXXXX X..",
"  X.XXooooooXooooooXoooooXXX X..",
"  X.XXooooooXooooooXooooooXX X..",
"  X.XXooXXXXXXXooXXXooXXXooX X..",
"  X.XXooXXXXXXXooXXXooXXXooX X..",
"  X.XXooooXXXXXooXXXooooooXX X..",
"  X.XXooooXXXXXooXXXoooooXXX X..",
"  X.XXooXXXXXXXooXXXooXXXXXX X..",
"  X.XXooXXXXXXXooXXXooXXXXXX X..",
"  X.XXooXXXXXXXooXXXooXXXXXX X..",
"  X.XXooXXXXXXXooXXXooXXXXXX X..",
"  X.XXXXXXXXXXXXXXXXXXXXXXXX X..",
"  X.XXXXXXXXXXXXXXXXXXXXXXXX X..",
"  X.XXXXX XXXXXXXXXXXX XXXXX X..",
"  X.XXXX  XXXXXXXXXXXX  XXXX X..",
"  X.XXX  X            X  XXX X..",
"  X.XX  XX            XX  XX X..",
"  X.X  XXXXXXXXXXXXXXXXXX  X X..",
"  X.XX..XX............XX..XX X..",
"  X.XXX..X............X..XXX X..",
"  X.XXXX..XXXXXXXXXXXX..XXXX X..",
"  X.XXXXX.XXXXXXXXXXXX.XXXXX X..",
"  X.                         X..",
"  XXXXXXXXXXXXXXXXXXXXXXXXXXXX..",
"  ..............................",
" ..............................."};
