/* XPM */
static char * ghostview_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconGray4	m white	c #949494949494",
"X	s iconGray3	m white	c #adadadadadad",
"o	s iconGray5	m black	c #737373737373",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray6	m black	c #636363636363",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray1	m white	c #dededededede",
"$	s iconColor3	m black	c red",
"%	s iconGray8	m black	c #212121212121",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"             ....               ",
"          XX......ooo           ",
"        OXXX......ooo++         ",
"       OOXXX......ooo+++        ",
"       OOXXX......ooo++@@       ",
"      OOOXXX......ooo+++@       ",
"      OOOXXX......ooo++@@@      ",
"      #OOX$$$....$$$o+++@@      ",
"     #OOOXX$$.....$$o++@@@      ",
"     ##OOXXX......ooo+++@%%     ",
"     #OOOXXX......ooo++@@@%     ",
"     ##OOXXX......ooo+++@%%     ",
"     #OOOXXX......ooo++@@@%     ",
"    ###OOXXX......ooo+++@%%%    ",
"    ##OOOXX%%%%%%%%oo++@@@%%    ",
"    ###OOX%$$$$$$$$#o+++@%%%    ",
"    ##OOOXX########oo++@@@%%    ",
"    ###OOXXX......ooo+++@%%%    ",
"    ##OOOXXX......ooo++@@@%%    ",
"    ###OOXXX......ooo+++@%%%    ",
"    ##OOOXXX......ooo++@@@%%    ",
"    ###OOXXX......ooo+++@%%%    ",
"    ##OOOXXX......ooo++@@@%%    ",
"    ### OXX ... ..o o++ @%%     ",
"    ##   X   .   .   +   @      ",
"                                ",
"                                ",
"                                "};
