/* XPM */
static char * Html_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 5 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s none	m none	c none",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor1	m black	c black",
"O	s iconGray7	m black	c #424242424242",
/* pixels */
"                         .......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXoXXXXXXXXXXXXXXXoXXXXo.......",
" XoXoXoXoooXoooXoXXXoXXXo.......",
" oXXoooXXoXXoooXoXXXXoXXo.......",
" XoXoXoXXoXXoXoXoooXoXXXo.......",
" XXoXXXXXXXXXXXXXXXoXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXoOOXOooXoOOoXXOOXoXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXoOOooOoXOooXooOOoooXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXooXoOXOOooXOOOOXooXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXooXOOXoooXoXXOXOoXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXoOOOXoOOXoooXXOOOoXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXOXOOoOOXOOXoOOoXoXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXooXOoXooXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" oooooooooooooooooooooooo......."};
