/* XPM */
static char * Html_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"25 32 8 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	c #C8C8C8C8C8C8",
"X	s iconColor1	m black	c black",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	c #969696969696",
"@	c #4B4B4B4B4B4B",
"#	c #7D7D7D7D7D7D",
/* pixels */
"                         ",
" .......................X",
" .......................X",
" ...o...............o..OX",
" ..o.o.o.ooo.o.o.o..Oo.OX",
" .oOOoOoOOoOOoooOoOOO.oOX",
" o.OOoooOOoOOoOoOoOOOO.oX",
" .oOOoOoOOoOOoOoOoOOOOoOX",
" ..oOoOoOOoOOoOoOoooOo.OX",
" ..OoOOOOOOOOOOOOOOOo..OX",
" ......................OX",
" .......................X",
" ...+XX.@@.XX.@@.XX+@...X",
" .......................X",
" ...X+@@.X@@@@.X@@X###..X",
" .......................X",
" ...@.@@+@@.@@+@@.@@....X",
" .......................X",
" ...+XX.X+@.X.X+@.X@X+..X",
" .......................X",
" ...@X@.+XX@@.+XX@.@@+..X",
" .......................X",
" ...X@@.X.XX@.X.XX......X",
" .......................X",
" .......................X",
" .....X.@@.XX.@@.XX+@...X",
" .......................X",
" ...X+@@.X@@@@.X@@X.##..X",
" .......................X",
" .......................X",
" .......................X",
" XXXXXXXXXXXXXXXXXXXXXXXX"};
