/* XPM */
static char * latex_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 5 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s topShadowColor	m white	c #bdbdbdbdbdbd",
"X	s background	m black	c #949494949494",
"o	s iconColor1	m black	c black",
"O	s bottomShadowColor	m black	c #636363636363",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"        ................................        ",
"        ................................        ",
"        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        ",
"        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        ",
"        ooooXXXoXXooooooooXXXXoooXXXXooo        ",
"        XooXXXoooXoXXooXXoXXXXXooXXXXXoX        ",
"        XooXXXoooXXXXooXoooooooXooXXXoXX        ",
"        XooXXoXXooXXXooXXooXXXoXXooXoXXX        ",
"        XooXXoooooXXXooXXooXXXXXXXooXXXX        ",
"        XooXoXXXXooXXooXXooXXoXXXXoooXXX        ",
"        XoooooXXooooXooXXoooooXXXoXXooXX        ",
"        XooXXXXoXXXXXooXXooXXoXXoXXXXooX        ",
"        ooooooooXXXXooooXooXXXoooXXXXooo        ",
"        XXXXXXXXXXXXXXXXXooXXXoXXXXXXXXX        ",
"        XXXXXXXXXXXXXXXXoooooooXXXXXXXXX        ",
"        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        ",
"        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        ",
"        OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO        ",
"        OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO        ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
