/* XPM */
static char * mcvert_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor2	m white	c white",
"o	s iconGray1	m white	c #dededededede",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray6	m black	c #636363636363",
"%	s iconGray7	m black	c #424242424242",
"&	s iconColor5	m black	c blue",
/* pixels */
"             .                  ",
"            .X.                 ",
"           .XXX.                ",
"          .XXX..                ",
"         .XXX.X.                ",
"        .XXXXX..                ",
"         .XXXXX.                ",
"          .XXX.                 ",
" ........................       ",
".ooOOO+++@@@@@@@@###$$$%%.      ",
".ooOOO+++@@@@@@@@###$$$%%.      ",
" ........................       ",
"  .ooOOO+++@@@@###$$$%%.        ",
"  .ooOOO+++@@@@###$$$%%.        ",
"  .ooOOO+++@@@@###$$$%%.....    ",
"  .ooOOO+++@@@@###$$$%%.....    ",
"  .ooOOO+++@@@@###$$$%%.   .    ",
"  .ooOOO+++@@@@###$$$%%.   .    ",
" ........................  .&&&&",
".ooOOO+++@@@@@@@@###$$$%%. .&&&&",
".ooOOO+++@@@@@@@@###$$$%%.      ",
" ........................       ",
"             .                  ",
".....        .                  ",
".XX.o.       .            &&&&  ",
".XX.oo.  .  . .  .        &&&&  ",
".XX.... ....   ....  .........  ",
".XXXXX.  .       .  .OOOOOOOO.  ",
".X&X&X.             .OOOOOOOO.  ",
".XX&&X.             .OOOOOOOO.  ",
".XXXXX.             .OOOOOOOO.  ",
".......             ..........  "};
