/* XPM */
static char * Movie_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 6 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s background	m black	c #949494949494",
"o	s iconColor3	m black	c red",
"O	s iconColor5	m black	c blue",
"+	s iconColor4	m white	c green",
/* pixels */
"   .........................    ",
"   .  .XooooXXOOXXXXXXXX.  .    ",
"   ....oooooOOOOOO+++XXX....    ",
"   ....oooooOOOOOOO+++XX....    ",
"   .  .ooooOOOOOOOO+++XX.  .    ",
"   ....ooooOOOOOOOO+++XX....    ",
"   ....XooooOOOOOOO+++XX....    ",
"   .  .XXXXXOOOOOOO++XXX.  .    ",
"   ....XXXXXXOOOOOXXXXXX....    ",
"   ....XXXXXXXXXXXXXXXXX....    ",
"   .  ...................  .    ",
"   .........................    ",
"   .........................    ",
"   .  .XXXXXXXXXXXXXXXXX.  .    ",
"   ....XXooooXXOOXXXXXXX....    ",
"   ....XoooooOOOOOO+++XX....    ",
"   .  .XoooooOOOOOOO+++X.  .    ",
"   ....XooooOOOOOOOO+++X....    ",
"   ....XooooOOOOOOOO+++X....    ",
"   .  .XXooooOOOOOOO+++X.  .    ",
"   ....XXXXXXOOOOOOO++XX....    ",
"   ....XXXXXXXOOOOOXXXXX....    ",
"   .  ...................  .    ",
"   .........................    ",
"   .........................    ",
"   .  .XXXXXXXXXXXXXXXXX.  .    ",
"   ....XXXooooXXOOXXXXXX....    ",
"   ....XXoooooOOOOOO+++X....    ",
"   .  .XXoooooOOOOOOO+++.  .    ",
"   ....XXooooOOOOOOOO+++....    ",
"   ....XXooooOOOOOOOO+++....    ",
"   .  .XXXooooOOOOOOO+++.  .    "};
