/* XPM */
static char * netscape_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 -1 -1",
/* colors */
" 	c #000037373C3C",
".	c #1A1A5F5F6767",
"X	c #000080808080",
"o	c #42429A9AA7A7",
"O	c #C0C0C0C0C0C0",
"+	c #808080808080",
"@	s iconColor2	m white	c white",
"#	s iconColor7	m white	c cyan",
"$	s iconColor1	m black	c black",
"%	c #BABAA0A0A7A7",
"&	c #2F2F7E7E8888",
"*	c #808080800000",
/* pixels */
"      .   . .                        . .        ",
"              . .      .   .  .          . .    ",
". . .  . . ..  . . . .  ..  .  .. . . .   . . . ",
" . .  . . .  ..   .   . . .....  . . .  ..   .  ",
". . .. . . X.. ...  . .. ... . ...... X.. . .  .",
" . .. . . .. .. . .. . ... ..... . . .. .. . .. ",
".. .. .. . ...... .. ..... .......... ... ..... ",
" .. ... ... . ................ ... .... .... ...",
".. . . ... .... .. ..... ..........X.... . .. . ",
"....................................X.X.........",
".X...X...X...X.... ..X.X.X.X.X..X. X.X.X.XXX.. .",
"X.X.X.X.X.X.X.X.X.X.X..XXXX.X.X.X.X.X.X.X.X.X.X.",
".X.X.X.X.X.X.X.X.X.X.ooOO+oX.X.X.X.X.X.X.X.X.X.X",
"X.X.X.X.X.X.X.X.X.X.oOO@#@+o..X.X.X.X.X.X.X.X.X.",
".X.X.X.X.X.X.X.X.X..oO#oX#@+.X.X.X.X.X.X.X.X.X.X",
"X.X.X.X.XXXXXXXXXXXXO@OoXX@+$ XXXXXXXXXXXXX.X.X.",
".X.XXXXXXXXXXXXXXXX.o@Oo X#%$$ XXXXXXXXXXXXXXX.X",
"XXXXXXXXXXXXXXXXXXX.O@Oo XO+$  XXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXX&o@oo X@+$$.XXXXXXXXXXXXXXXXX",
"XXXoXXXoXXXoXXXoXXXoo@Oo #O+$  oXXXoXXXoXXXoXXXo",
"XoXXXoXXXoXXXoXXXoXXoO@& OO.$  XXoXXXoXXXoXXXoXX",
"XXXoXXXoXXXoXXXoXXXo&O@o @O$  .oXXXoXXXoXXXoXXXo",
".oXXXoXXXoXXXoXXXoXXXo@o @o$$ XXXoXXXoXXXoXXXoXX",
"o&ooXXXoXXXoXXXoXXXoXO@O @%$$ XoXXXoXXXoXXXoXXoo",
"@O&XXoXXXoXXXoXXXoXXXO@o @O.$ XXXoXXXoXXXoXXXoXO",
"@Oo.oXoXoXoXoXoXoXXoo@@o #O. .oXoXoXoXoXoXoXoX@@",
"#@O .oXoXoXoXXXoXoo#OO@o O@+++&oooXoXoXoXoXoXO@#",
"o@@+ .oXoXoXXoooOO@@@@@ooO@@@OO+oooXoXoXoXXXo@@O",
" #@O$ .oXXXooO@@@@O. .   ....o@@@O+ooXXoXXo#O@#.",
". O@%$ oooO@@@Oo. . . . . .....XoO@O+oooooXO@@. ",
"o. @@%+.+OO@Oo.  . . . . ...&.&...oO@O+oo+O@@. &",
"@O. @@O++O@o    . . . . . .&o&.X..oXo@O++O@@. oO",
"+OO. #@@@O&. . . . . . ....o.o&&X&.o.XO@O@#. oO%",
" +@o.&O@o.  . . . . ...&&o.&...o.&o&&&Xo@#. o@%.",
"$ +@o&oo.  . . . . ....o....o.&&oo&.&XX&o.&oOO $",
"$$ O@Oo   . . . ....&o%o&oOoo.&Xoo.&.oXX&Xo@O.$$",
"$$ O@O   . . . ..oOOOOOO&@@OOOoo&ooooo&&X&XoO $$",
"$ +OOX  . . . ooOO+.+O@o&#O+.+%OOo&oo.o&&.Xo@+ $",
"$ OOo  . . ..oOO+ $$.O@o&@O+$$ +OOoo.o&.&XX&OO+$",
" +@o  . . &.&@@%.$$$+O@o&#@O $$ +@@oX.o&o&.X&@% ",
".OO. . .o.o.o@@O%$$ +@oo.#O%$$.OO@@O&oooo.&&&oO+",
"+@o . ...XoOoo#@@O. +O#o.o@+ .%@@#oXoooX.o&X&&@%",
"OO . ...ooO@O. o#@% .O@o&o@. O@@#ooo@@ooo.o&&&oO",
"@o. . X&.OOO@o.oo#@+ %@o&#O*+O@Oooo#OOOXoo&o&&#O",
"O. . &.&oO..OOo.oO@%++@o&@%.%@@.o.o@%.OOo#o&o&&#",
"o . ...&O% $+@O .&#@%+@o&@%+@@o.&o@O $+@o&oo&&o#",
" . .&.&oO.$$ %@# .o@@OOO&@@O@oo&o@O.$$.Ooo#&o&&#",
". ..&XooO $ $ +OO ..@@@#o#@@ooo@O+ $$$ +@X&o#ooo"};
