/* XPM */
static char * netscape_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 11 1 0 0",
/* colors */
" 	c #000037373C3C",
".	c #1A1A5F5F6767",
"X	c #000080808080",
"o	c #42429A9AA7A7",
"O	c #C0C0C0C0C0C0",
"+	s iconColor7	m white	c cyan",
"@	s iconColor2	m white	c white",
"#	s iconColor1	m black	c black",
"$	c #2F2F7E7E8888",
"%	c #808080808080",
"&	c #BABAA0A0A7A7",
/* pixels */
"   . ..                 ",
"...   .     . . .... ...",
"...   . . .. .  ...X... ",
". ..  .... .. ..........",
".   . ... .. .......  ..",
"......... ......X ...X. ",
"...........oOo..........",
"..........o+X@..........",
"..XXXXXXXXoO +# XXXXXXX.",
"XXXXXXXXXXoo @#.XXXXXXXX",
"XXXXXXXXXXo@ O# XXXXXXXX",
".XXXXXXXXXX@ o#XXXXXXXXX",
"@$XXXXXXXXX@ O#XXXXXXXXX",
"+O.XXXXXXoO@ @%$oXXXXXX@",
" @#.XXo@@O   ..@@%oXXoO+",
"o @%%OO.     .$$.o@%oO@ ",
"%O @@$      ...$X..OO+ O",
"#%oo.     ....o$o$$Xo$O ",
"# @     .OOO$@Oo$oo$XXO#",
"#Oo   .O%#.@$O# Oo.$$XO%",
".O  ooo@&#%o.O#.O@$oo$$O",
"O  .oOO +&.@$@ @+o@ooo$o",
"O  .o.Ooo@%@$&&@oo&Oooo$",
"  $$O# @ o@O$@@ooO#.o+o$"};
