/* XPM */
static char * netscape_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	c #000037373C3C",
".	c #1A1A5F5F6767",
"X	c #000080808080",
"o	c #42429A9AA7A7",
"O	c #C0C0C0C0C0C0",
"+	c #808080808080",
"@	s iconColor7	m white	c cyan",
"#	s iconColor2	m white	c white",
"$	s iconColor1	m black	c black",
"%	c #BABAA0A0A7A7",
"&	c #2F2F7E7E8888",
"*	c #808080800000",
/* pixels */
"    .  ..                ..     ",
"           .      . .        .  ",
" .. .  . .  .  .. ... .  . .  . ",
".  . .. ....   . ..  .... ...   ",
"....... ................. ......",
" . .. ... .......... .. .. .....",
"........................X.......",
".X....X..X.. .X..XX.... .XX.XX. ",
".XX..XX..XX..XooO+X..XX..XX..XX.",
"X..XX..XX..XX.OO@#o.X..XX..XX..X",
"X..XX.XXXXXXXX#OXX+$XXXXXXXXX..X",
".XXXXXXXXXXXX.#O X%$ XXXXXXXXXX.",
"XXXXXXXXXXXXX&#o X+$.XXXXXXXXXXX",
"XXoXXoXXXXoXXo#O @+$ oXXXXoXXoXX",
"XXoXXoXXXXoXXoO# #$ .oXXXXoXXoXX",
".oXXXXoXXoXXXXo# #$$XXoXXoXXXXoX",
"#OXXXXoXXoXXXXO# #.$XXoXXoXXXXoX",
"#O.ooXXooXXoXo## @. oXXooXXooXX#",
"o#+ oXXoXooO####oO##O+oooXXoXX##",
" @O$.oXXoO##O..  ...##O+oXoXo@#@",
"o.##+.OOOo   ..  ..&&..o#OooO#. ",
"#O #O+O#   ..  .. &o.X.oo#++## o",
" +o.O#. .  .. ..&o&..o&o&&o#. #%",
"$ #ooo   ..  ......o&&o&&X&o&oO ",
"$$O#  .  ...OOOO&#OOoooooo&XXo $",
"$ OO   .. oO+.O#&@+.%Oo&o.&&Xo+ ",
" +o .  &&#%.$$O#&@O $ ##X.&o.X#%",
".O.  ..oo#O%$ #o.@%$.O##&ooo&&oO",
"OO. ..oOO.o@% O#&o. ##oo##ooo&&o",
"#o .X&OO#ooo#+%#&@*+#OooOOXo&o&@",
"o  ..&% +# .@#+#&#+#o.o# $#ooo&o",
" ..&&o.$ %@ o#OO&#O#o&#O$$Oo@&&&"};
