/* XPM */
static char * wabi_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 3 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray5	m black	c #737373737373",
"X	s iconColor6	m white	c yellow",
/* pixels */
"                     ......     ",
"                 ..........     ",
"             ........XXXX..     ",
"         ........XXXXXXXX..     ",
"     ........XX..XXXXXXXX..     ",
"     ....XXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXX.....     ",
"     ..XXXXXXXX..XX........     ",
"     ..XXXXXXXX........XX..     ",
"     ..XXXXXX......XXXXXX..     ",
"     ..XX........XXXXXXXX..     ",
"     ........XX..XXXXXXXX..     ",
"     ....XXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXXXXXX..     ",
"     ..XXXXXXXX..XXXX......     ",
"     ..XXXXXXXX............     ",
"     ..XXXXX.........           ",
"     ............               ",
"     ........                   ",
"     ...                        "};
