/* XPM */
static char * wabi_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 3 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor6	m white	c yellow",
/* pixels */
"                                ........        ",
"                             ...........        ",
"                          ..............        ",
"                      ..................        ",
"                   .............XXXX....        ",
"                .............XXXXXXX....        ",
"              ............XXXXXXXXXX....        ",
"           ...............XXXXXXXXXX....        ",
"       ............XXX....XXXXXXXXXX....        ",
"       .........XXXXXX....XXXXXXXXXX....        ",
"       .......XXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXX.......        ",
"       ....XXXXXXXXXXX....XXXX..........        ",
"       ....XXXXXXXXXXX....XX............        ",
"       ....XXXXXXXXXXX..................        ",
"       ....XXXXXXXXXXX...........XXX....        ",
"       ....XXXXXXXX...........XXXXXX....        ",
"       ....XXXXX............XXXXXXXX....        ",
"       ....XX.............XXXXXXXXXX....        ",
"       ...................XXXXXXXXXX....        ",
"       ............XXX....XXXXXXXXXX....        ",
"       .........XXXXXX....XXXXXXXXXX....        ",
"       ......XXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXXXXXX....        ",
"       ....XXXXXXXXXXX....XXXXXX........        ",
"       ....XXXXXXXXXXX....XXX...........        ",
"       ....XXXXXXXXXXX..................        ",
"       ....XXXXXXXXXXX..............            ",
"       ....XXXXXXXX.............                ",
"       ....XXXXX.............                   ",
"       ....XXX............                      ",
"       ...............                          ",
"       ............                             ",
"       .........                                ",
"       .......                                  "};
