/* XPM */
static char * WordPerfect_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 4 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor2	m white	c white",
"o	c #00007F7FBFBF",
/* pixels */
"           .................    ",
"          .XXXXXXXXXXXXXXXXX..  ",
"          .XXXXXXXXXXXXXXXXXXX. ",
"   ooooooo.X..XX..X...XX..X.XX. ",
" ooooooooooooX..X.....X..XX.XX. ",
"oooooooooooooooXXXXXXXXXXXX...  ",
"    ooooooooooooX..XX....XX.    ",
"       oooooooooooo...X..XX.    ",
"       ooooooooooooXXXXXXXX.    ",
"        ooooooooooooXX...XX.    ",
"        ..ooooooooooooX..XX.    ",
"        .XooooooooooooXXXXX.    ",
"        .Xooooooooooooo..XX.    ",
"       .XXoooooooooooooooX.     ",
"       .XXXooooooooooooooX.     ",
"       .XXXooooooooooooooX.     ",
"       XX..Xoooooooooooooo      ",
"      .XXXXXXooooooooooooo      ",
"      .X..X.Xooooooooooooo      ",
"     .X..X...ooooooooooooo      ",
"    .XXXXXXXXXooooooooooo       ",
"    .XX...XX.XXoooooooooo       ",
"   .XX......X...XXXXXXoo        ",
"   .XXXXXXXXXXXXXXXXXXooo       ",
"   .X....X....XX.Xoooooooooo    ",
"   .X..X..XX....XXXoooooooo     ",
"   .XXXXXXXXXXXXXXoooooooXoo    ",
"   .X...XX...XX.XXoooooooXoo    ",
"   .XX.XX..XX...Xoooooooooooo   ",
"   .XXXXXXXXXXXXXoooooooooooo   ",
"    ..............ooooooooooo   ",
"                                "};
