/* XPM */
static char * WordPerfect_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 4 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor2	m white	c white",
"o	c #00007F7FBFBF",
/* pixels */
"                 .........................      ",
"                 .........................      ",
"               ..XXXXXXXXXXXXXXXXXXXXXXXXX...   ",
"               ..XXXXXXXXXXXXXXXXXXXXXXXXXXXX.. ",
"               ..XXXXXXXXXXXXXXXXXXXXXXXXXXXX.. ",
"     oooooooooo..X...XXX...XX....XXX...XX.XXX.. ",
"  ooooooooooooooooooX...XX.......XX...XXX.XXX.. ",
"  ooooooooooooooooooX...XX.......XX...XXX.XXX.. ",
"oooooooooooooooooooooooXXXXXXXXXXXXXXXXXX....   ",
"      ooooooooooooooooooXX...XXX......XXX.      ",
"      ooooooooooooooooooXX...XXX......XXX.      ",
"           oooooooooooooooooo....XX...XXX.      ",
"           ooooooooooooooooooXXXXXXXXXXXX.      ",
"            ooooooooooooooooooXXX.....XXX.      ",
"            ooooooooooooooooooXXX.....XXX.      ",
"            ...ooooooooooooooooooXX...XXX.      ",
"            ..XooooooooooooooooooXXXXXXXX.      ",
"            ..XooooooooooooooooooXXXXXXXX.      ",
"            ..Xoooooooooooooooooooo...XXX.      ",
"           .XXXoooooooooooooooooooooooX..       ",
"           .XXXoooooooooooooooooooooooX..       ",
"           .XXXXXoooooooooooooooooooooX..       ",
"           .XXXXXoooooooooooooooooooooX..       ",
"           XXX...Xooooooooooooooooooooo         ",
"           XXX...Xooooooooooooooooooooo         ",
"         ..XXXXXXXXXooooooooooooooooooo         ",
"         ..X...XX.XXooooooooooooooooooo         ",
"         ..X...XX.XXooooooooooooooooooo         ",
"        .XX...X.....ooooooooooooooooooo         ",
"      ..XXXXXXXXXXXXXooooooooooooooooo          ",
"      ..XXXXXXXXXXXXXooooooooooooooooo          ",
"      ..XXX....XXX..XXXooooooooooooooo          ",
"     .XXX.........XX....XXXXXXXXXooo            ",
"     .XXX.........XX....XXXXXXXXXooo            ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXXXXooooo          ",
"     .XX......X......XXX..Xooooooooooooooo      ",
"     .XX...X...XXX......XXXXXoooooooooooo       ",
"     .XX...X...XXX......XXXXXoooooooooooo       ",
"     .XXXXXXXXXXXXXXXXXXXXXoooooooooooXooo      ",
"     .XX....XXX.....XXX.XXXoooooooooooXooo      ",
"     .XX....XXX.....XXX.XXXoooooooooooXooo      ",
"     .XXX..XXX...XXX....XXoooooooooooooooooo    ",
"     .XXXXXXXXXXXXXXXXXXXXoooooooooooooooooo    ",
"     .XXXXXXXXXXXXXXXXXXXXoooooooooooooooooo    ",
"      .....................ooooooooooooooooo    ",
"                                                ",
"                                                ",
"                                                "};
