/* XPM */
static char * xdvi_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 6 1 -1 -1",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconColor1	m black	c black",
"X	s iconColor5	m black	c blue",
"o	s iconColor2	m white	c white",
"O	s iconGray8	m black	c #212121212121",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
/* pixels */
"                                ",
"                                ",
"  ..  .   ....  ..    . ......  ",
"   ...    ..  .  ..   .   ..    ",
"    ..    ..  .   .. .    ..    ",
"   . ..   ..  .   .. .    ..    ",
"  .   ..  ....     ..   ......  ",
"                                ",
"                                ",
"                                ",
"                   XXXX         ",
"                 XXXXXXXX       ",
"                XXXooooXXX      ",
"                XXooooooXX      ",
"   ooooooooooooXXoooOOOooXXo    ",
"   oOOooOOo+OOoXXooOooOooXXo    ",
"   o+++oOOooOOoXXoooOOOooXXo    ",
"   o+++oOOooOOoXXXooOOOoXXXo    ",
"   oooooooooooooXXXooooXXXoo    ",
"   oOOoOOOooooooXXXXXXXXXooo    ",
"   oOOo+oooOooo.XXXXXXXooooo    ",
"   oOOo+oooOooX.Xooooooooooo    ",
"   ooooooooooXXXoooooooooooo    ",
"   oOOOoOOoo..XoOO+oOOo+++oo    ",
"   oOO+ooooXXXoo++Oo++oOoooo    ",
"   oOO+oooXXXooo++Oo++oOoooo    ",
"   ooooooX.Xoooooooooooooooo    ",
"   oOOOoXXXo++Oo++o+++o+OOoo    ",
"   oooOooXooOOOo++OooooO++oo    ",
"   oooOoooooOOOo++OooooO++oo    ",
"   ooooooooooooooooooooooooo    ",
"   ooooooooooooooooooooooooo    "};
