/* XPM */
static char * Xfig_h_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 64 6 1 -1 -1",
/* colors */
" 	s iconColor1	m black	c black",
".	c #3F3FBFBFFFFF",
"X	c #7F7FBFBF3F3F",
"o	c #8B8B45451313",
"O	c #00007F7F0000",
"+	s iconColor2	m white	c white",
/* pixels */
"                                                                ",
" .............................................................. ",
" ...........................................  ................. ",
" .......       . .........................  X  ................ ",
" ........ .... . ........................ XXXXX ............... ",
" ........ .... ........  ...............  XXXXX ............... ",
" ........ .. ..  ...   ................ XXXXXXX ............... ",
" ........    ... .. ... ............... XXXXXXXX .............. ",
" ........ .. ... .. ... .............  XXXXXXXXX .............. ",
" ........ ...... ...   .............. XXXXXXXXXX .............. ",
" ........ ...... ... ............... XXXXXXXXXXX .............. ",
" .......   ....   ..    ............ XXXXXXXXXX ....  ......... ",
" ..   ............. .... .......... XXXXXXXXXXX ... XX  ....... ",
" .. oo   .......... .... .......... XXXXXXXXXXX .. XXXXX  ..... ",
" .. oooo  ..........    ........... XXXXXXX XXX   XXXXXXXX .... ",
" .. oooooo    ..................   XXXXXXX XXXXXXXXXXXXXXXX ... ",
" ..  ooooooooo   .......        ooo XXXXXX XXXXXXXXXXXXXXXXX .. ",
" ...   oooooooooo       oooooooooo  XXXXX XXXXXXXXXX XXXXXXXX . ",
" ......    oooooooooooooooooooo   XXXXX  XXXXXXX X  XXXXXXXXX . ",
" ..........    oooo   ooooo     XXXX XXXXXXXXX XXXXXXXXXXXXXX . ",
" ..............     O         XXXXX + XXX    XXXXXXXXXXXXXXXX . ",
" ................. OO ...   XXXXXX X X  XXXXXXXXXXXXXXXXXXXXX . ",
" ................  O .... XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX . ",
" ................ OO .... XXXXXX  XXX XXX XXXXXXXXXXXXXXXXXXX . ",
" ...............  OO .... XXXXX XXXXX XXXX XXXXXX     XXXXXX .. ",
" .............. OOO .... XXXXX XXXXXX XXXXX XXXX .... XXXXX ... ",
" ............. OOOO ... XXXXXXXXXXXXX XXXXXXXXXX ..... XXXX ... ",
" ............. OOO ... XXXXXXXXXXXXXX XXXXXX  XXX   .. XX  .... ",
" ............. OOO .. XXXXXXXXX   XXXXXXXXXXX XXXXXX ..  ...... ",
" ............. OOO .. XXXXXXX  ... XX XXXXXXXX XXXXXX ......... ",
" ............ OOOO ..  XXXXXX ..   XX XXXXXXXX XXXXXX ......... ",
" ........... OOOOO ...       .. XXXXX XXXXXXXXXXXXXXXX ........ ",
" .......... OOOOOOO ........... XXXX XXXXXXXXXXXXXXXXX ........ ",
" ......... OOOOOOOO .........  XXXXX XXXXXXXXXXXXXXXXXX ....... ",
" ......... OOOOOOOOO ....... XXXXXXX XXXXXXXXXX XXXXXXXX ...... ",
" ........ OOOOOOOOOO ....... XXXXXX XXXXXXXXXXXXXXXXXXXX ...... ",
" ....... OOOOOOOOOOOO ...... XXXXX XXXX  XXXXXXX XXXXXXX ...... ",
" ...... OOOOOOOOOOOOO ..... XXXXX XXXX .. XXXXXX XXXXXXXX ..... ",
" ...... OOOOOOOOOOOOOO .... XXXXXXXXX ... XXXXXX XXXXXXXX ..... ",
" ..... OOOOO OOOOOOOOO ...  XXXXXXXXX .. XXXXXXX XXXXXXXX ..... ",
" ..... OOOO OOOOOOOOOOO .. XXXXXXXXXX .. XXXXXXXXXXXXXXXX ..... ",
" .... OOOOOOOOOOOOOOOOO .. XXXXXXXXXX . XXXXXXXXX XXXXXXX ..... ",
" .... OOOO OOOOOOOOOOOO .. XXXXXXXXX .. XXXXXXXXXXXXXXXXX ..... ",
" ... OOOOOOOOOOOOOOOOOO .. XXXXXXXX ... XXXXXXXXX XXXXXXX ..... ",
" ... OOOO OOOOOOOOOOOOOO . XXXXXXX .... XXXXXXXXX XXXXXXX ..... ",
" .. OOOOOOOOOOOOOOOOOOOO .. XXXX  ..... XXXXXXXXXXXXXXXXX ..... ",
" .. OOOOO OOOOOOOOOOOOOO ...    ....... XXXXXXXXXXXXXXXXX ..... ",
" .. OOOOOOOOOOOOOOOOOOOO .............. XXXXXXXXXXXXXXXX ...... ",
" . OOOOOO OOOOOOOOOOOOOOO ............. XXXXXXXXXXXXXXXX ...... ",
" . OOOOOOOOOOOOOOOOOOOOOO ............. XXXXXXXXXXXXXXX ....... ",
" . OOOOOOO OOOOOOOOOOOOOO .............. XXXXXXXXXXXXXX ....... ",
" .. OOOOOOOOOOOOOOOOOOOOO ............... XXXXXXXXXXXXX ....... ",
" .. OOOOOOOOOOOOOOOOOOOOO ............... XXXXXXXXXXXX ........ ",
" .. OOOOOOOOO  OOOOOOOOO ................. XXXXXXXXXX ......... ",
" .. OOOOOOOO ++OOOOOOOOO .................. XXXXXXXX .......... ",
" ... OOOOOOO ++OOOOOOOO ....................  XXXXX ........... ",
" ... OOOOOOOO  OOOOOOO ...................... XXXX ............ ",
" .... OOOOOOOOOOOOOOO ........................ XX ............. ",
" ..... OOOOOOOOOOOOO  .........................  .............. ",
" ...... OOOOOOOOOO   .......................................... ",
" .......   OOOO   ............................................. ",
" .........     ................................................ ",
" ...............................................................",
"                                                                "};
