/* XPM */
static char * Xfig_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 6 1 -1 -1",
/* colors */
" 	c #3F3FBFBFFFFF",
".	s iconColor1	m black	c black",
"X	c #7F7FBFBF3F3F",
"o	c #8B8B45451313",
"O	c #00007F7F0000",
"+	s iconColor2	m white	c white",
/* pixels */
"                                ",
"                      .         ",
"                     .X.        ",
"                    .XXX.       ",
"                   .XXXX.       ",
"                  .XXXXX.       ",
"  ..              .XXXX.  ...   ",
"  oo...           .XXXXX..XXX.  ",
"  ..ooo...........XXX.XXXXXXXX. ",
"    ..oooooooooo.XXX.XXX..XXXX. ",
"      ....O....XXX+XX..XXXXXXX. ",
"         ..  .XXXX.X.XXXXXXXXX. ",
"        .O. .XXXXXXXX.XXX..XXX. ",
"       .OO  .XXXXXXXXXXX.  .X.  ",
"       .O. .XXX..XXXXXXXXX. .   ",
"      .OO. .XX. ..XXXXX.XXX     ",
"      .OO.  .. .XX.XXXXXXXX.    ",
"     .OOOO.   .XXX.XXXXXXXXX.   ",
"    .OOOOOO.  .XX.X..XXX.XXX.   ",
"   .OOOOOOO.  .XXX.  .XX.XXXX.  ",
"   .OOOOOOO. .XXXX. .XXXXXXXX.  ",
"  .OO.OOOOO. .XXXX. .XXXXXXXX.  ",
"  .OOOOOOOOO..XXX.  .XXXXXXXX.  ",
"  .OOOOOOOOO. ...   .XXXXXXXX.  ",
" .OOOOOOOOOOO.      .XXXXXXX.   ",
" .OOO.OOOOOOO.      .XXXXXXX.   ",
"  .OOOOOOOOOO.       .XXXXX.    ",
"  .OOO.+OOOO.         .XXX.     ",
"  .OOOO.OOO.           .X.      ",
"   .OOOOOO.             .       ",
"    ......                      ",
"                                "};
