/* XPM */
static char * Xfig_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 6 1 0 0",
/* colors */
" 	c #3F3FBFBFFFFF",
".	s iconColor1	m black	c black",
"X	c #7F7FBFBF3F3F",
"o	c #8B8B45451313",
"O	c #00007F7F0000",
"+	s iconColor2	m white	c white",
/* pixels */
"                                                ",
"                                                ",
"                                 ..             ",
"                               ..XX.            ",
"                              ..XXX.            ",
"                             .XXXXXX.           ",
"                            ..XXXXXX.           ",
"                            .XXXXXXX.           ",
"                           .XXXXXXXX.  ..       ",
"   ..                      .XXXXXXX.  .XX.      ",
"   .o..                    .XXXXXXX.  .XXX..    ",
"   .oo.....             ....XXXXXXXX..XXXXXX.   ",
"   .ooooooo..     ......oooXXXXX.XXXXXXXXXXXX.  ",
"   ...ooooooo.....oooooooo.XXXX.XXXXXXX.XXXXXX. ",
"      ...ooooooooooooooo..XXXX.XXXXX.X.XXXXXXX. ",
"         ......O.......XXXX+.XX...XXXXXXXXXXXX. ",
"              .O.  ..XXXXX..X.XXXXXXXXXXXXXXXX. ",
"             ...   .XXXXXXX.XX.XXXXXXXXXXXXXXX. ",
"            ..O.   .XXXXXXXX.XXX.XXXX....XXXX.  ",
"            .O.   .XXXX.XXXX.XXXXXXX.   .XXXX.  ",
"           .OO.  .XXXXXXXXXX.XXXXXXX.    .XXX.  ",
"           .OO. .XXXXXXX..XXXXXXXX.XX...  ...   ",
"           .OO. .XXXXX..  .X.XXXXXX.XXXX.       ",
"          .OOO. ..XXXX. ...X.XXXXXX.XXXX.       ",
"         .OOOO.   .... .XXX.XXXXXXXXXXXXX.      ",
"        .OOOOO.       ..XXX.XXXXXXXXXXXXXX.     ",
"       ..OOOOOO.     .XXXXX.XXXXXXXXXXXXXX.     ",
"      .OOOOOOOOO.    .XXXX.XXX.XXXXX.XXXXX.     ",
"      .OOOOOOOOO.   .XXXX.XXX. .XXXX.XXXXXX.    ",
"      .OOOOOOOOOO.  .XXXXXXX.  .XXXX.XXXXXX.    ",
"     .OOOOOOOOOOO.  .XXXXXXX. .XXXXXXXXXXXX.    ",
"    .OOOOOOOOOOOOO. .XXXXXXX. .XXXXXX.XXXXX.    ",
"    .OOO.OOOOOOOOO. .XXXXXX. .XXXXXXXXXXXXX.    ",
"   .OOO.OOOOOOOOOO. .XXXXX.  .XXXXXXX.XXXXX.    ",
"   .OOOOOOOOOOOOOO. .XXX..   .XXXXXXXXXXXXX.    ",
"  .OOOO.OOOOOOOOOO.  ...     .XXXXXXXXXXXXX.    ",
"  .OOOO.OOOOOOOOOOO.         .XXXXXXXXXXXX.     ",
"  .OOOOOOOOOOOOOOOO.         .XXXXXXXXXXXX.     ",
"  .OOOOO.OOOOOOOOOO.          .XXXXXXXXXXX.     ",
"  .OOOOOOOOOOOOOOOO.           .XXXXXXXXX.      ",
"   .OOOOOO..OOOOOO.             .XXXXXXX.       ",
"   .OOOOO.++OOOOOO.              .XXXXX.        ",
"   .OOOOOO..OOOOO.                .XXX.         ",
"    .OOOOOOOOOOO.                  .X.          ",
"     .OOOOOOOOO..                   .           ",
"      ...OOO...                                 ",
"        ....                                    ",
"                                                "};
